export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nvim'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nvim'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $path
  /opt/{homebrew,local}/{,s}bin(N-/)
  /home/linuxbrew/.linuxbrew/{,s}bin(N-/)
  /usr/local/{,s}bin(N-/)
  ${HOME}/.local/bin(N-/)
  ${HOME}/.local/share/n/bin(N-/)
  ${HOME}/.local/share/pnpm(N-/)
)

fpath=(
  $fpath
  ${HOME}/.zsh/functions(N-/)
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# N - Node Version Manager
export N_PREFIX="${HOME}/.local/share/n"

# ----- [WSL PATH] -----

# Detect if running under WSL
if [[ -n "$WSL_DISTRO_NAME" ]] || [[ -n "$WSLENV" ]] || [[ "$(uname -r)" =~ (M|m)icrosoft ]]; then
  # WSL automatically appends Windows PATH, which can cause conflicts
  # We need to ensure WSL/Linux tools have priority over Windows tools
  
  # Save original PATH
  _original_path="$PATH"
  
  # Reset PATH with Linux-only paths
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  
  # Add WSL-specific paths in priority order
  path=(
    ${HOME}/.local/share/pnpm(N-/)
    ${HOME}/.local/share/n/bin(N-/)
    ${HOME}/.local/bin(N-/)
    /home/linuxbrew/.linuxbrew/bin(N-/)
    /home/linuxbrew/.linuxbrew/sbin(N-/)
    $path
  )
  
  # Extract and append Windows paths to the end
  if [[ "$_original_path" =~ /mnt/c ]]; then
    _win_paths=$(echo "$_original_path" | tr ':' '\n' | grep '^/mnt/c' | tr '\n' ':' | sed 's/:$//')
    if [[ -n "$_win_paths" ]]; then
      PATH="$PATH:$_win_paths"
    fi
  fi
  
  unset _original_path _win_paths
fi
