packages:
  darwin:
    brew:
      - zsh
      - reattach-to-user-namespace
      - git
      - tmux
      - thefuck
      - atuin
      - python
      - bitwarden-cli
      - blueutil
      - curl
      - ffmpeg
      - htop
      - imagemagick
      - iperf3
      - neofetch
      - neovim
      - pyenv
      - scrcpy
      - tldr
      - yt-dlp
      # - fzf
    cask:
      - airbuddy
      - android-platform-tools
      - devtoys
      - discord
      - dozer
      - drawio
      - epoch-flip-clock
      - ghostty
      - google-chrome
      - iina
      - iterm2
      - last-window-quits
      - microsoft-edge
      - monitorcontrol
      - obsidian
      - reqable
      - snipaste
      - topnotch
      - visual-studio-code
      - warp
      - bitwarden
    python:

    node:

  linux:
    internal:
      common:
        - build-essential
        - make
        - gcc
        - lsd
        - curl
        - git
        - zsh
        - neovim
        - htop
        - lsof
        - ffmpeg
        - neofetch
        - tldr
        - xclip
        - tmux # client only?
        - python3

      client:
        - nmap
        - cifs-utils
        - avahi-daemon

      server:

    brew:
      common:
        - atuin
        - thefuck
      client:
        - bitwarden-cli

      server:

    python:
      common:
        - "thefuck"

      client:

      server:

    node:
      common:
      macos:
        '@anthropic-ai/claude-code'
      linux:
        common:
        client:
          - '@anthropic-ai/claude-code'
        server:
          
